version: '3.7'
services:
  mysql:
    container_name: spring-boot-booking_mysql_1
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=booking
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080